### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by josephgupkim** [Markhenn/APIprojectthescoop#2]
I loved the addition of comments to your code base as it further aided in organization and legibility. Please do continue this for future projects as the code base gets larger; it will not only help yourself but those reading your code as well!

Don't forget you can use comments to title off sections of your code to increase its organized structured!

**Comment by Markhenn** [comment]
Thanks, using comments as a way to create sections in code is a very good idea. :) I'll start doing that.
